### ISSUE TITLE
"Agenda" is not the right translation in French

### ISSUE THREAD

**Issue by nicolinuxfr** [iainc/iA-Writer-Localization#1]
In the French translation, you're using "_Agenda_" for "_Organizer_". It's not false, but it is not the correct translation in this context. 

An "_agenda_" is more like a calendar, and not an organizer. 

Unfortunately, I don't have a great idea to suggest. We do have a direct translation, but "_Organisateur_" sounds more English than French.

**Comment by antons** [comment]
Thank you for bringing this up! We’ll rename it to “Organisateur”.
