### ISSUE TITLE
Spanish improvements es/Shared/Kit.strings

### ISSUE THREAD

**Issue by shawtux** [iainc/iA-Writer-Localization#2]
Some of the proposed texts are gramatically correct, but dont sound quite right. Do you want it like a formal text or more like a neutral?

**formal**
"Button_Try_Again" = "Inténtelo nuevamente"
"Unknown_Recovery_Suggestion" = "Por favor, vuelva a probar o contactese con soporte.";
"Web_Service_Publish_Status_Unlisted" = "Sin listar";

**neutral**
"Button_Try_Again" = "Intentalo nuevamente"
"Unknown_Recovery_Suggestion" = "Por favor, vuelve a probar o contactate con soporte.";
"Web_Service_Publish_Status_Unlisted" = "Sin listar";

**Comment by antons** [comment]
@shawtux With English, we try to match the tone set by Apple in iOS and macOS as much as we can. We’d prefer to do the same in other languages too.

**Comment by antons** [comment]
@shawtux What tone does Apple use in their apps?

**Comment by shawtux** [comment]
I'm sorry. I'm a windows user trying to help.
